# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37dff13dcd5003bb28905335d45b7e7f78ad82a57aa63e7b0b683f932753821e5365b5f90bb591c388e32d731d0927eb1580b61b53a30b1348027d9c0d5ab6dc

test:
  secret_key_base: efa1c2f3f50803fc0a8730c9c7380b177bae7f77e50517dc58653ab15624ec698f388e6076e6720d207336c5f736936b688f50e1848cbaab68caf3fdae72ffd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
